apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: openfaas-gateway
  namespace: openfaas
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`openfaas.home`)
      kind: Rule
      services:
        - name: gateway
          port: 8080
  tls: {}
