---
- name: "Install k3s using k3sup joining head with node: {{ ansible_default_ipv4.address }}"
  become: true
  command: "sudo k3sup join \
    --ip {{ ansible_default_ipv4.address }} \
    --user=raphael \
    --ssh-key {{ ssh_key_path }} \
    --sudo \
    --k3s-channel stable \
    --server \
    --server-ip {{ kube_vip_endpoint }} \
    --server-user {{ user }}"
  register: script_output
  delegate_to: localhost

- name: Wait for all k8s nodes to be ready
  command: "kubectl wait --for=condition=Ready nodes --all --timeout=600s"
  delegate_to: localhost
  register: nodes_ready

- debug: var=nodes_ready.stdout_lines
