- name: Set hostname for nodes
  become: true
  command:
    "sudo hostnamectl set-hostname '{{ hostname }}'"

- name: sudo without password
  become: true
  copy:
    dest: /etc/sudoers.d/ansible-user_rules
    content: '{{ user }} ALL=(ALL) NOPASSWD:ALL'
