# values.yaml

# Ingress Configuration
ingress:
  enabled: true
  hostname: wg.home  # Change this to the desired hostname

# WireGuard Configuration
wgHost: "90.61.204.229"
wgDefaultDNS: "192.168.1.1,1.1.1.1,8.8.8.8"
wgDefaultAddress: "192.168.1.x"
wgAllowedIps: "0.0.0.0/0,::/0"

# Service Configuration
service:
  type: LoadBalancer
  ports:
    wireguardUDP: 51820
    webUI: 51821

# Persistent Volume Configuration
pvc:
  enabled: true
  size: 1Gi
