---
- name: Select a single server node to run the command
  become: true
  command: "k3s etcd-snapshot save"
  register: snapshot_result

- name: Display the result of the snapshot command
  debug:
    var: snapshot_result.stdout

#- name: Save to AWS s3 bucket

  /var/lib/rancher/k3s/server/db/snapshots