---
- name: Stop K3s cluster with external PostgreSQL
  hosts: agent
  become: true
  tasks:
    - name: Stop K3s service on all agent nodes
      ansible.builtin.systemd:
        name: k3s-agent
        state: stopped

- name: Stop K3s cluster with external PostgreSQL
  hosts: server
  become: true
  tasks:
    - name: Stop K3s service on all server nodes
      ansible.builtin.systemd:
        name: k3s
        state: stopped