apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
      - name: etcd
        image: quay.io/coreos/etcd:v3.5.6
        ports:
        - containerPort: 2379
        command:
        - etcd
        - --listen-client-urls=http://0.0.0.0:2379
        - --advertise-client-urls=http://etcd.kube-system:2379
---
apiVersion: v1
kind: Service
metadata:
  name: etcd
  namespace: kube-system
spec:
  ports:
  - port: 2379
    targetPort: 2379
  selector:
    app: etcd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coredns-local
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: coredns-local
  template:
    metadata:
      labels:
        app: coredns-local
    spec:
      containers:
      - name: coredns
        image: coredns/coredns:1.10.1
        args: ["-conf", "/etc/coredns/Corefile"]
        volumeMounts:
        - name: config-volume
          mountPath: /etc/coredns
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
      volumes:
      - name: config-volume
        configMap:
          name: coredns-local-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-local-config
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        health
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
    }
    local:53 {
        errors
        cache 30
        etcd {
          path /skydns
          endpoint http://etcd.kube-system:2379
        }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: coredns-local
  namespace: kube-system
spec:
  selector:
    app: coredns-local
  ports:
  - name: dns
    port: 53
    protocol: UDP
  - name: dns-tcp
    port: 53
    protocol: TCP