# traefik-values.yaml
deployment:
  replicas: 1
  kind: DaemonSet

globalArguments:
  - "--global.checknewversion=false"
  - "--global.sendanonymoususage=false"

additionalArguments:
  - "--log.level=INFO"

ingressClass:
  enabled: true
  isDefaultClass: true

service:
  type: LoadBalancer
  ip: '192.168.1.183'

ports:
  web:
    port: 80
  websecure:
    port: 443
    tls:
      enabled: true

logs:
  general:
    level: INFO
  access:
    enabled: true

dashboard:
  enabled: true
  domain: "traefik.home"

metrics:
  prometheus:
    enabled: false
    serviceMonitor:
      enabled: false

ingressRoute:
  dashboard:
    enabled: true
    annotations: {}
    labels: {}
    matchRule: Host(`traefik.home`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
    services:
      - name: api@internal
        kind: TraefikService
    entryPoints: ["websecure"]
    middlewares:
      - name: dashboard-auth
      - name: ratelimit-dashboard
      - name: redirect-to-https
    tls: {}