apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: dashboard-auth
  namespace: traefik
spec:
  basicAuth:
    secret: authsecret
---
apiVersion: v1
kind: Secret
metadata:
  name: authsecret
  namespace: traefik
data:
  users: |-
    YWRtaW46JGFwcjEkNWR3OWRVcFckNzdiY1FaQ0VNVTJGZGNILzZTeS9yLw==

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-to-https
  namespace: traefik
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: ratelimit-dashboard
  namespace: traefik
spec:
  rateLimit:
    average: 100
    burst: 200
---



