apiVersion: apps/v1
kind: Deployment
metadata:
  name: openvpn
  labels:
    app: openvpn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openvpn
  template:
    metadata:
      labels:
        app: openvpn
    spec:
      serviceAccountName: openvpn
      containers:
        - name: openvpn
          image: "{{ .Values.image }}"
          ports:
            - containerPort: 443
            - containerPort: 943
            - containerPort: 1194
          volumeMounts:
            - mountPath: /openvpn
              name: openvpn-config
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            capabilities:
              add: ["NET_ADMIN"]
      volumes:
        - name: openvpn-config
          persistentVolumeClaim:
            claimName: openvpn-pvc
