apiVersion: v1
kind: PersistentVolume
metadata:
  name: openvpn-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/openvpn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openvpn-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
