---
k3s_cluster:
  children:
    server:
      hosts:
        192.168.1.51:
        192.168.1.52:
        192.168.1.53:
    agent:
      hosts:
        192.168.1.48:
        192.168.1.49:

  vars:
    ansible_port: 22
    ansible_user: raphael
    k3s_version: v1.30.2+k3s1
    kube_vip_endpoint: "192.168.1.144"
    interface: "enX0"
    token: "Lu9VHNSAMZhIaujd8hob0V3XqRgI2lm8qap9ad+HY5jH7qKQvLlXyTnk5fL76KNTOHlbCq62weUE0wz+sQuZPw=="
    api_endpoint: "{{ hostvars[groups['server'][0]]['ansible_host'] | default(groups['server'][0]) }}"
    use_external_database: true
    cluster_context: "galideo"
    extra_server_args: "--datastore-endpoint=postgres://admin:admin@192.168.1.50:5432/k3s --disable=traefik --disable=servicelb --flannel-iface=enX0 --tls-san=192.168.1.144"
    extra_agent_args: ""
