---
- hosts: raspberries
  become: true

  tasks:
    - name: Update package lists
      apt: update_cache=yes

    - name: Upgrade installed packages
      apt: upgrade=yes

    - name: Install htop package
      package:
        name: htop
        state: present

    - name: Install zsh package
      package:
        name: zsh
        state: present

    - name: Set zsh as default shell
      user:
        name: raphael
        shell: /bin/zsh

    - name: Disable swap
      command: swapoff -a
      ignore_errors: yes

    - name: Add cgroup configuration to the filesystem
      lineinfile:
        path: /boot/firmware/cmdline.txt
        line: cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1
