apiVersion: v1
kind: ConfigMap
metadata:
  name: snmp-exporter-config
  namespace: monitoring
data:
  snmp_exporter.yml: |
    scrape_configs:
      - job_name: ilo_exporter
        scrape_interval: 5s
        metrics_path: /metrics
        static_configs:
          - targets: ['192.168.1.80']
