apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-storage
  namespace: default
  # labels:
  #   app: postgres
  #   tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
