replicaCount: 1

DNS1: 192.168.1.1
DNS2: "1.1.1.1"

# # Disable hostPort since we're using LoadBalancer
# dnsHostPort:
#   enabled: false
serviceDhcp:
  enabled: false

serviceDns:
  type: LoadBalancer
  loadBalancerIP: "192.168.1.181"
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole
  externalTrafficPolicy: Local
  mixedService: true
  port: 53

# Web interface configuration
serviceWeb:
  http:
    enable: true
    port: 80
    type: LoadBalancer
  type: ClusterIP

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128M

ingress:
  enabled: true
  annotations: {}
  path: /
  pathType: ImplementationSpecific
  hosts:
    - pihole.home
  tls: []

persistence:
  enabled: true
  storageClass: "longhorn"
  accessModes:
    - ReadWriteOnce
  size: 1Gi

persistentVolumeClaim:
  enabled: true
  annotations: {}
  accessModes:
    - ReadWriteOnce
  size: "500Mi"
  storageClass: "longhorn"

extraEnvVars:
  ServerIP: "192.168.1.181"
  DNSMASQ_LISTENING: "all"
  TZ: "Europe/Paris"