DNS1:
  192.168.1.1

persistentVolumeClaim:
  enabled: true

ingress:
  enabled: true
  hosts:
    - "pihole.home"

serviceWeb:
  loadBalancerIP: 192.168.1.220
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer

serviceDns:
  loadBalancerIP: 192.168.1.219
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer

replicaCount: 1
