apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wg-easy.fullname" . }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
