services:
  homeLab-backend:
    container_name: back
    image: velocipastor/homelab_server:latest
    ports:
      - "8080:6000"
    env_file:
      - .env.back
    volumes:
      - ./.env.back:/app/.env
    depends_on:
      - redis
    networks:
      - back

  redis:
    image: redis:latest
    container_name: redis
    command: [ "redis-server", "--requirepass", "superSecurePassword" ]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - back

#  frontend:
#    container_name: front
#    image: homelab_frontend:latest
#    ports:
#      - "3000:3000"
#    env_file:
#      - .env.front

volumes:
  redis-data:

networks:
  back: