apiVersion: v1
kind: Secret
metadata:
  name: private-bgd-repo
  namespace: argo-cd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/christianh814/private-bgd
  password: ${GITHUB_TOKEN}
  username: not-used