#!/usr/bin/env just --justfile

install_all_helm_chart:
  helm repo add longhorn https://charts.longhorn.io
  helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
  helm repo add grafana https://grafana.github.io/helm-charts
  helm repo add bitnami https://charts.bitnami.com/bitnami
  helm repo add argo https://argoproj.github.io/argo-helm
  helm repo add mojo2600 https://mojo2600.github.io/pihole-kubernetes/
  helm repo update

deploy:
  just deploy_metalLB
  just deploy_longhorn
  just deploy_monitoring
  just deploy_argo
  just deploy_piHole
  just deploy_externalDNS

deploy_metalLB:
    kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.14.8/config/manifests/metallb-native.yaml
    kubectl apply -f ./metalLb/addressPool.yml

deploy_longhorn:
  helm install longhorn longhorn/longhorn --namespace longhorn-system -f ./longhorn/values.yml --create-namespace

deploy_monitoring:
    helm install prometheus prometheus-community/prometheus -n monitoring --create-namespace
    helm install grafana grafana/grafana -f ./grafana/values.yaml -n monitoring

deploy_argo:
  helm install argo-cd argo/argo-cd -f ./argo/values.yml -n argo-cd --create-namespace

deploy_piHole:
  helm install pihole mojo2600/pihole -f ./pihole/values.yml -n system-dns --create-namespace

deploy_externalDNS:
  helm install external-dns bitnami/external-dns -f ./externalDNS/values.yml -n system-dns --create-namespace

deploy_redis:
  helm install home-lab-redis bitnami/redis -f ./redis/values.yaml -n home-lab --create-namespace

# Test App
deploy_test_app:
    kubectl apply -f ../example/deployment.yml
    kubectl apply -f ../example/service.yml

delete_test_app:
    kubectl delete -f ../example/deployment.yml
    kubectl delete -f ../example/service.yml
    kubectl get deployments
    kubectl get svc