---
- name: Deploy MetalLb native
  kubernetes.core.k8s:
    state: present
    src: https://raw.githubusercontent.com/metallb/metallb/v0.14.8/config/manifests/metallb-native.yaml
  delegate_to: localhost
  run_once: true

- name: Deploy MetalLb configMap
  kubernetes.core.k8s:
    state: present
    src: "{{ role_path }}/files/metalLB.configMap.yml"
  delegate_to: localhost
  run_once: true

- name: Deploy MetalLb configMap
  command: "kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.12.1/manifests/metallb.yaml"
  delegate_to: localhost
  run_once: true
  ignore_errors: yes

- name: Deploy Longhorn via Helm
  kubernetes.core.helm:
    name: longhorn
    chart_ref: longhorn/longhorn
    release_namespace: longhorn-system
    values_files:
      - "{{ role_path }}/files/longhorn.yml"
    create_namespace: true
    state: present
  register: longhorn_result
  delegate_to: localhost
  run_once: true

- name: Display Helm result
  debug:
    msg: "{{ longhorn_result }}"